


# Feature Engineering — Encode, Transform & Prepare Data for Stroke Prediction

## Business Question


How can we transform the cleaned stroke dataset into a machine-learning-ready dataset while preserving important clinical information and avoiding data leakage?

---

## Why This Step Matters


Machine learning models cannot work effectively with raw categorical variables such as gender, work type, or smoking status. Feature engineering converts these variables into numerical representations while creating additional clinically meaningful features that may improve model performance.



This notebook prepares the dataset for predictive modelling by:

- Encoding categorical variables into numerical format.
- Creating clinically meaningful age, glucose, and BMI categories.
- Preserving important continuous variables.
- Preparing a model-ready dataset.
- Delaying SMOTE until the modelling stage to avoid data leakage.

In [5]:
# =====================================================
# SECTION 2: IMPORT LIBRARIES
# =====================================================

# pandas is used for loading and manipulating datasets.
import pandas as pd

# numpy provides numerical functions that support data analysis.
import numpy as np

# LabelEncoder converts binary categorical variables
# into numerical values that machine learning models
# can understand.
from sklearn.preprocessing import LabelEncoder

# Display all columns when viewing DataFrames.
pd.set_option("display.max_columns", None)

In [6]:
# =====================================================
# SECTION 3: LOAD CLEANED DATASET
# =====================================================

# Load the cleaned stroke dataset produced during
# the data cleaning stage.
#
# This dataset already has:
# - Missing BMI values handled.
# - Duplicate records removed.
# - Correct data types.
# - Clean categorical values.

df = pd.read_csv(
    "/content/drive/MyDrive/PERSONAL PROJECTS/MENTORSHIP PROJECTS/1 Stroke Risk Prediction & Clinical Insights Analysis/stroke_cleaned.csv"
)

# Display the first five rows to confirm that the
# dataset loaded successfully.

df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

# Dataset Overview

Before creating new features, it is important to understand the current structure of the dataset.

This section verifies:

- Number of rows and columns.
- Variable names.
- Data types.
- Presence of the variables required for feature engineering.

Performing these checks helps ensure that the dataset is ready for transformation and reduces the likelihood of errors later in the notebook.

In [7]:
# =====================================================
# SECTION 5: CHECK DATASET SHAPE
# =====================================================

# Display the number of rows and columns.
#
# This confirms that all observations have been loaded
# successfully.

df.shape

(5110, 11)

In [8]:
# =====================================================
# SECTION 6: VIEW COLUMN NAMES
# =====================================================

# Display all column names.
#
# This helps confirm that the variables required for
# feature engineering are available.

df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [9]:
# =====================================================
# SECTION 7: CHECK DATA TYPES
# =====================================================

# Display the data type of every variable.
#
# Categorical variables will later be encoded into
# numerical format for machine learning.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             5110 non-null   object
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64
 3   heart_disease      5110 non-null   int64
 4   ever_married       5110 non-null   object
 5   work_type          5110 non-null   object
 6   Residence_type     5110 non-null   object
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   object
 10  stroke             5110 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB

In [10]:
# =====================================================
# SECTION 8: PREVIEW DATASET
# =====================================================

# Display a random sample of five records.
#
# This provides another opportunity to verify that the
# dataset has loaded correctly before feature engineering
# begins.

df.sample(5, random_state=42)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
4688,Male,31.0,0,0,No,Self-employed,Rural,64.85,23.0,Unknown,0
4478,Male,40.0,0,0,Yes,Self-employed,Rural,65.29,28.3,never smoked,0
3849,Female,8.0,0,0,No,children,Urban,74.42,22.5,Unknown,0
4355,Female,79.0,1,0,Yes,Self-employed,Rural,76.64,19.5,never smoked,0
3826,Female,75.0,0,0,Yes,Govt_job,Rural,94.77,27.2,never smoked,0

# Section 9: Encode Binary Categorical Variables

## Business Question

How can we convert binary categorical variables into numerical values that machine learning algorithms can understand?

---

## Why This Step Matters

Machine learning algorithms cannot directly interpret text values such as **Male**, **Female**, **Yes**, **No**, **Urban**, or **Rural**.

Label Encoding converts these text categories into numbers while preserving all the information.

Since these variables have only two categories, Label Encoding is the most appropriate technique.

The variables to be encoded are:

- gender
- ever_married
- Residence_type

In [11]:
# =====================================================
# SECTION 10: LABEL ENCODING
# =====================================================

# Create a LabelEncoder object.
#
# This object converts text values into numerical values.
# Example:
#
# Male   -> 1
# Female -> 0
#
# The exact numbers assigned are determined automatically.

label_encoder = LabelEncoder()

# -----------------------------------------------
# Encode the Gender column
# -----------------------------------------------

# Convert Male/Female into numerical values.

df["gender"] = label_encoder.fit_transform(df["gender"])

# -----------------------------------------------
# Encode Ever Married
# -----------------------------------------------

# Convert:
#
# Yes -> 1
# No  -> 0

df["ever_married"] = label_encoder.fit_transform(df["ever_married"])

# -----------------------------------------------
# Encode Residence Type
# -----------------------------------------------

# Convert:
#
# Urban
# Rural
#
# into numerical values.

df["Residence_type"] = label_encoder.fit_transform(df["Residence_type"])

# Display the first five rows to verify the changes.

df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.0,0,1,1,Private,1,228.69,36.6,formerly smoked,1
1,0,61.0,0,0,1,Self-employed,0,202.21,28.1,never smoked,1
2,1,80.0,0,1,1,Private,0,105.92,32.5,never smoked,1
3,0,49.0,0,0,1,Private,1,171.23,34.4,smokes,1
4,0,79.0,1,0,1,Self-employed,0,174.12,24.0,never smoked,1

In [12]:
# =====================================================
# SECTION 11: VERIFY LABEL ENCODING
# =====================================================

# Display only the encoded columns.
#
# This helps confirm that the binary categorical
# variables have been converted successfully.

df[
    [
        "gender",
        "ever_married",
        "Residence_type"
    ]
].head()

   gender  ever_married  Residence_type
0       1             1               1
1       0             1               0
2       1             1               0
3       0             1               1
4       0             1               0

## Interpretation

The binary categorical variables have now been successfully converted into numerical values.

These transformations allow machine learning algorithms to process the variables while preserving the original information contained in each category.

Since each variable contains only two categories, Label Encoding is an appropriate and efficient encoding technique.

# Section 12: One-Hot Encode Multi-category Variables

## Business Question

How can we convert categorical variables with multiple categories into a format suitable for machine learning without introducing artificial ordering?

---

## Why This Step Matters

Unlike binary variables, columns such as **work_type** and **smoking_status** contain several categories.

If Label Encoding were applied to these variables, the model might incorrectly assume that one category is greater than another.

For example:

Private = 0

Government Job = 1

Self-employed = 2

This would incorrectly introduce an order that does not exist.

Instead, One-Hot Encoding creates a separate binary column for each category, allowing the model to treat every category independently.

In [13]:
# =====================================================
# SECTION 13: ONE-HOT ENCODING
# =====================================================

# Unlike binary variables, work_type and smoking_status
# contain multiple categories.
#
# Applying Label Encoding to these variables would
# incorrectly introduce an order between categories.
#
# One-Hot Encoding creates a separate binary column
# for each category while preserving all information.

# ----------------------------------------------
# One-Hot Encode work_type
# ----------------------------------------------

# Create dummy variables for each work type.
# drop_first=False keeps every category so that
# no information is lost.

work_type_encoded = pd.get_dummies(
    df["work_type"],
    prefix="work_type",
    drop_first=False
)

# ----------------------------------------------
# One-Hot Encode smoking_status
# ----------------------------------------------

# Create dummy variables for each smoking status.

smoking_encoded = pd.get_dummies(
    df["smoking_status"],
    prefix="smoking_status",
    drop_first=False
)

# ----------------------------------------------
# Add the encoded columns back to the dataset
# ----------------------------------------------

df = pd.concat(
    [df, work_type_encoded, smoking_encoded],
    axis=1
)

# ----------------------------------------------
# Remove the original categorical columns
# ----------------------------------------------

# These columns are no longer needed because
# their information is now stored in the newly
# created binary columns.

df.drop(
    columns=[
        "work_type",
        "smoking_status"
    ],
    inplace=True
)

# Display the first five rows to verify the changes.

df.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,1,67.0,0,1,1,1,228.69,36.6,1,False,False,True,False,False,False,True,False,False
1,0,61.0,0,0,1,0,202.21,28.1,1,False,False,False,True,False,False,False,True,False
2,1,80.0,0,1,1,0,105.92,32.5,1,False,False,True,False,False,False,False,True,False
3,0,49.0,0,0,1,1,171.23,34.4,1,False,False,True,False,False,False,False,False,True
4,0,79.0,1,0,1,0,174.12,24.0,1,False,False,False,True,False,False,False,True,False

In [14]:
# =====================================================
# SECTION 14: VERIFY ONE-HOT ENCODING
# =====================================================

# Display only the newly created columns
# to confirm that the encoding was successful.

encoded_columns = [

    column

    for column in df.columns

    if column.startswith("work_type_")

    or column.startswith("smoking_status_")

]

df[encoded_columns].head()

,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,False,False,True,False,False,False,True,False,False
1,False,False,False,True,False,False,False,True,False
2,False,False,True,False,False,False,False,True,False
3,False,False,True,False,False,False,False,False,True
4,False,False,False,True,False,False,False,True,False

## Interpretation

The multi-category variables have now been successfully transformed using One-Hot Encoding.

Instead of assigning numerical labels that could imply an artificial order, each category is represented by its own binary column.

This allows machine learning models to learn the influence of each category independently while avoiding incorrect assumptions about relationships between categories.

At the same time, the original categorical columns have been removed because their information is now fully represented by the newly created binary variables.

# Section 15: Create Age Band Feature

## Business Question

Can grouping patients into clinically meaningful age bands help the model better capture differences in stroke risk?

---

## Why This Step Matters

Although the original age variable will remain in the dataset, creating age bands may help machine learning algorithms recognise non-linear patterns that are difficult to capture using age alone.

Based on the exploratory data analysis, stroke risk increased substantially among older patients.

The following age bands will therefore be created:

- Less than 40 years
- 40 to 60 years
- Above 60 years

Importantly, the original continuous **age** variable will remain in the dataset, following the mentor's recommendation to preserve important clinical measurements.

In [15]:
# =====================================================
# SECTION 16: CREATE AGE BAND FEATURE
# =====================================================

# Create age categories based on clinically
# meaningful age groups identified during EDA.

df["age_band"] = pd.cut(

    df["age"],

    bins=[0, 40, 60, 120],

    labels=[

        "<40",

        "40-60",

        "60+"

    ]

)

# Display a sample of the new feature.

df[
    [
        "age",
        "age_band"
    ]
].head(10)

    age age_band
0  67.0      60+
1  61.0      60+
2  80.0      60+
3  49.0    40-60
4  79.0      60+
5  81.0      60+
6  74.0      60+
7  69.0      60+
8  59.0    40-60
9  78.0      60+

## Interpretation

A new categorical feature named **age_band** has been created.

This engineered feature groups patients into clinically meaningful age categories while preserving the original continuous age variable.

Keeping both variables allows predictive models to benefit from precise numerical age values as well as broader age-related risk patterns identified during exploratory data analysis.

# Section 17: Create Glucose Risk Tier

## Business Question

Can grouping patients according to their blood glucose levels help the predictive model identify clinically meaningful patterns associated with stroke risk?

---

## Why This Step Matters

Average glucose level is already available as a continuous numerical variable.

However, clinicians often interpret glucose measurements using recognised risk categories rather than exact numbers alone.

Creating glucose risk tiers allows the model to learn both:

- The exact glucose measurement (continuous variable).
- The patient's clinical risk category (engineered feature).

Following the mentor's recommendation, the original **avg_glucose_level** variable will remain in the dataset.

The glucose categories are:

- **Normal:** Less than 100 mg/dL
- **Pre-diabetic:** 100–125 mg/dL
- **Diabetic:** Greater than 125 mg/dL

In [16]:
# =====================================================
# SECTION 18: CREATE GLUCOSE RISK TIER
# =====================================================

# Create clinically meaningful glucose categories.
#
# We use pd.cut() to divide continuous glucose values
# into three clinical risk groups.

df["glucose_risk_tier"] = pd.cut(

    df["avg_glucose_level"],

    bins=[0, 100, 125, float("inf")],

    labels=[
        "Normal",
        "Pre-diabetic",
        "Diabetic"
    ]

)

# Display a sample of the original glucose values
# alongside the newly created glucose risk tier.

df[
    [
        "avg_glucose_level",
        "glucose_risk_tier"
    ]
].head(10)

   avg_glucose_level glucose_risk_tier
0             228.69          Diabetic
1             202.21          Diabetic
2             105.92      Pre-diabetic
3             171.23          Diabetic
4             174.12          Diabetic
5             186.21          Diabetic
6              70.09            Normal
7              94.39            Normal
8              76.15            Normal
9              58.57            Normal

## Interpretation

A new feature called **glucose_risk_tier** has been created.

This feature groups patients into clinically recognised glucose categories while preserving the original continuous glucose measurements.

Keeping both variables allows machine learning models to learn from both the exact glucose values and the broader clinical risk categories.

# Section 19: Create BMI Category

## Business Question

Can grouping Body Mass Index (BMI) into standard clinical categories improve the model's ability to identify stroke risk?

---

## Why This Step Matters

BMI is already available as a continuous variable.

However, healthcare professionals usually interpret BMI using standard clinical categories.

Creating BMI categories allows the model to capture obesity-related risk patterns while still preserving the original BMI measurements.

Following the mentor's recommendation, the original **bmi** variable will remain in the dataset.

The BMI categories are:

- Underweight (<18.5)
- Normal (18.5–24.9)
- Overweight (25–29.9)
- Obese (30+)

In [17]:
# =====================================================
# SECTION 20: CREATE BMI CATEGORY
# =====================================================

# Create clinically meaningful BMI categories.
#
# These categories are based on standard WHO BMI
# classifications.

df["bmi_category"] = pd.cut(

    df["bmi"],

    bins=[0, 18.5, 25, 30, float("inf")],

    labels=[
        "Underweight",
        "Normal",
        "Overweight",
        "Obese"
    ]

)

# Display a sample of the original BMI values
# together with the newly created BMI category.

df[
    [
        "bmi",
        "bmi_category"
    ]
].head(10)

    bmi bmi_category
0  36.6        Obese
1  28.1   Overweight
2  32.5        Obese
3  34.4        Obese
4  24.0       Normal
5  29.0   Overweight
6  27.4   Overweight
7  22.8       Normal
8  28.1   Overweight
9  24.2       Normal

## Interpretation

A new feature called **bmi_category** has been created.

This feature groups patients according to standard clinical BMI classifications while preserving the original BMI measurements.

Retaining both variables provides the predictive model with detailed numerical information as well as clinically meaningful categories.

In [18]:
# =====================================================
# SECTION 21: VERIFY ENGINEERED FEATURES
# =====================================================

# Display a selection of important variables
# to confirm that feature engineering has been
# completed successfully.

df[
    [
        "age",
        "age_band",
        "avg_glucose_level",
        "glucose_risk_tier",
        "bmi",
        "bmi_category"
    ]
].head(10)

    age age_band  avg_glucose_level glucose_risk_tier   bmi bmi_category
0  67.0      60+             228.69          Diabetic  36.6        Obese
1  61.0      60+             202.21          Diabetic  28.1   Overweight
2  80.0      60+             105.92      Pre-diabetic  32.5        Obese
3  49.0    40-60             171.23          Diabetic  34.4        Obese
4  79.0      60+             174.12          Diabetic  24.0       Normal
5  81.0      60+             186.21          Diabetic  29.0   Overweight
6  74.0      60+              70.09            Normal  27.4   Overweight
7  69.0      60+              94.39            Normal  22.8       Normal
8  59.0    40-60              76.15            Normal  28.1   Overweight
9  78.0      60+              58.57            Normal  24.2       Normal

# =====================================================
# SECTION 21: VERIFY ENGINEERED FEATURES
# =====================================================

# Display a selection of important variables
# to confirm that feature engineering has been
# completed successfully.

df[
    [
        "age",
        "age_band",
        "avg_glucose_level",
        "glucose_risk_tier",
        "bmi",
        "bmi_category"
    ]
].head(10)

In [19]:
# =====================================================
# SECTION 23: SAVE MODEL-READY DATASET
# =====================================================

# Save the feature-engineered dataset.
#
# At this stage:
# - Original continuous variables have been retained.
# - New engineered features have been added.
# - No SMOTE has been applied.
#
# This dataset is now ready for predictive modelling.

df.to_csv(
    "/content/drive/MyDrive/PERSONAL PROJECTS/MENTORSHIP PROJECTS/1 Stroke Risk Prediction & Clinical Insights Analysis/stroke_model_ready.csv",
    index=False
)

print("✅ Model-ready dataset saved successfully.")

✅ Model-ready dataset saved successfully.

In [20]:
# =====================================================
# SECTION 24: VERIFY FINAL DATASET
# =====================================================

# Display the first five rows of the final
# feature-engineered dataset.

df.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,age_band,glucose_risk_tier,bmi_category
0,1,67.0,0,1,1,1,228.69,36.6,1,False,False,True,False,False,False,True,False,False,60+,Diabetic,Obese
1,0,61.0,0,0,1,0,202.21,28.1,1,False,False,False,True,False,False,False,True,False,60+,Diabetic,Overweight
2,1,80.0,0,1,1,0,105.92,32.5,1,False,False,True,False,False,False,False,True,False,60+,Pre-diabetic,Obese
3,0,49.0,0,0,1,1,171.23,34.4,1,False,False,True,False,False,False,False,False,True,40-60,Diabetic,Obese
4,0,79.0,1,0,1,0,174.12,24.0,1,False,False,False,True,False,False,False,True,False,60+,Diabetic,Normal

In [21]:
# =====================================================
# SECTION 25: DOWNLOAD DATASET (OPTIONAL)
# =====================================================

# This cell allows you to download the final
# model-ready dataset directly from Google Colab.

from google.colab import files

files.download(
    "/content/drive/MyDrive/PERSONAL PROJECTS/MENTORSHIP PROJECTS/1 Stroke Risk Prediction & Clinical Insights Analysis/stroke_model_ready.csv"
)

# Section 26: Feature Engineering Summary

## Overview

The cleaned stroke dataset has been transformed into a machine-learning-ready dataset through a series of feature engineering steps. These transformations improve the dataset's suitability for predictive modelling while preserving clinically important information.

---

## Summary of Feature Transformations

| Feature | Transformation | Reason |
|----------|----------------|--------|
| **gender** | Label Encoding | Converts binary text values into numerical values that machine learning algorithms can process. |
| **ever_married** | Label Encoding | Encodes Yes/No responses into numerical format. |
| **Residence_type** | Label Encoding | Converts Urban/Rural categories into numerical values. |
| **work_type** | One-Hot Encoding | Creates separate binary columns for each work category without introducing artificial ordering. |
| **smoking_status** | One-Hot Encoding | Creates independent binary columns for each smoking category while preserving all information. |
| **age_band** | Feature Engineering | Groups patients into clinically meaningful age categories identified during exploratory analysis. |
| **glucose_risk_tier** | Feature Engineering | Categorises glucose measurements into Normal, Pre-diabetic, and Diabetic risk groups. |
| **bmi_category** | Feature Engineering | Groups BMI values into standard WHO clinical categories. |
| **age** | Retained | Preserves the original continuous age measurement for predictive modelling. |
| **avg_glucose_level** | Retained | Preserves the exact glucose measurement alongside the engineered risk tier. |
| **bmi** | Retained | Preserves the original BMI measurement while also using BMI categories. |

---

## Key Outcomes

- Binary categorical variables were successfully encoded using Label Encoding.
- Multi-category variables were transformed using One-Hot Encoding.
- New clinically meaningful features were created for age, glucose level, and BMI.
- Original continuous variables (**age**, **avg_glucose_level**, and **bmi**) were retained, following the mentor's recommendation.
- The final dataset has **not** been balanced using SMOTE to prevent data leakage.
- The dataset is now fully prepared for predictive modelling, where SMOTE will be applied **only to the training data** after the train-test split.